//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace Kinovea.Updater.Languages {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class UpdaterLang {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UpdaterLang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("Kinovea.Updater.Languages.UpdaterLang", typeof(UpdaterLang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software Update….
        /// </summary>
        internal static string mnuCheckForUpdates {
            get {
                return ResourceManager.GetString("mnuCheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version is available!.
        /// </summary>
        internal static string Updater_Behind {
            get {
                return ResourceManager.GetString("Updater_Behind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose the target directory for the installer file..
        /// </summary>
        internal static string Updater_BrowseFolderDescription {
            get {
                return ResourceManager.GetString("Updater_BrowseFolderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Destination Folder.
        /// </summary>
        internal static string Updater_ChooseDestinationFolder {
            get {
                return ResourceManager.GetString("Updater_ChooseDestinationFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Version :.
        /// </summary>
        internal static string Updater_CurrentVersion {
            get {
                return ResourceManager.GetString("Updater_CurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string Updater_Download {
            get {
                return ResourceManager.GetString("Updater_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading New Version....
        /// </summary>
        internal static string Updater_Downloading {
            get {
                return ResourceManager.GetString("Updater_Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Size :.
        /// </summary>
        internal static string Updater_FileSize {
            get {
                return ResourceManager.GetString("Updater_FileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while checking for updates. Please ensure an Internet connection is available. .
        /// </summary>
        internal static string Updater_InternetError {
            get {
                return ResourceManager.GetString("Updater_InternetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Log :.
        /// </summary>
        internal static string Updater_LblChangeLog {
            get {
                return ResourceManager.GetString("Updater_LblChangeLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new version was successfully downloaded.\n Please close Kinovea and launch the installer from where you saved it. .
        /// </summary>
        internal static string Updater_mboxDownloadSuccess_Description {
            get {
                return ResourceManager.GetString("Updater_mboxDownloadSuccess_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MB.
        /// </summary>
        internal static string Updater_MegaBytes {
            get {
                return ResourceManager.GetString("Updater_MegaBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Version.
        /// </summary>
        internal static string Updater_NewVersion {
            get {
                return ResourceManager.GetString("Updater_NewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        internal static string Updater_Quit {
            get {
                return ResourceManager.GetString("Updater_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kinovea - Checking for new version..
        /// </summary>
        internal static string Updater_Title {
            get {
                return ResourceManager.GetString("Updater_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your version is up to date !.
        /// </summary>
        internal static string Updater_UpToDate {
            get {
                return ResourceManager.GetString("Updater_UpToDate", resourceCulture);
            }
        }
    }
}
