//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace Kinovea.Services.Properties {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class Resources {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("Kinovea.Services.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ColorProfiles.
        /// </summary>
        internal static string ColorProfilesFolder {
            get {
                return ResourceManager.GetString("ColorProfilesFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HelpVideos.
        /// </summary>
        internal static string HelpVideosFolder {
            get {
                return ResourceManager.GetString("HelpVideosFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manuals.
        /// </summary>
        internal static string ManualsFolder {
            get {
                return ResourceManager.GetString("ManualsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences.xml.
        /// </summary>
        internal static string PreferencesFile {
            get {
                return ResourceManager.GetString("PreferencesFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HelpIndex.xml.
        /// </summary>
        internal static string URILocalHelpIndex {
            get {
                return ResourceManager.GetString("URILocalHelpIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.kinovea.org/setup/update.xml.
        /// </summary>
        internal static string URIRemoteHelpIndex {
            get {
                return ResourceManager.GetString("URIRemoteHelpIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.kinovea.org/setup/updatebeta.xml.
        /// </summary>
        internal static string URIRemoteHelpIndexBeta {
            get {
                return ResourceManager.GetString("URIRemoteHelpIndexBeta", resourceCulture);
            }
        }
    }
}
