//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Configuration;
using System.Diagnostics;
using System.Runtime.CompilerServices;

namespace Kinovea.Services.Properties {
    
    
    [CompilerGenerated()]
    [GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("Preferences.xml")]
        public string PreferencesFile {
            get {
                return ((string)(this["PreferencesFile"]));
            }
            set {
                this["PreferencesFile"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("")]
        public string HistoryVideo1 {
            get {
                return ((string)(this["HistoryVideo1"]));
            }
            set {
                this["HistoryVideo1"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("")]
        public string HistoryVideo2 {
            get {
                return ((string)(this["HistoryVideo2"]));
            }
            set {
                this["HistoryVideo2"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("")]
        public string HistoryVideo3 {
            get {
                return ((string)(this["HistoryVideo3"]));
            }
            set {
                this["HistoryVideo3"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("")]
        public string HistoryVideo4 {
            get {
                return ((string)(this["HistoryVideo4"]));
            }
            set {
                this["HistoryVideo4"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("")]
        public string HistoryVideo5 {
            get {
                return ((string)(this["HistoryVideo5"]));
            }
            set {
                this["HistoryVideo5"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("")]
        public string HistoryVideo6 {
            get {
                return ((string)(this["HistoryVideo6"]));
            }
            set {
                this["HistoryVideo6"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("")]
        public string HistoryVideo7 {
            get {
                return ((string)(this["HistoryVideo7"]));
            }
            set {
                this["HistoryVideo7"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("")]
        public string HistoryVideo8 {
            get {
                return ((string)(this["HistoryVideo8"]));
            }
            set {
                this["HistoryVideo8"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("")]
        public string HistoryVideo9 {
            get {
                return ((string)(this["HistoryVideo9"]));
            }
            set {
                this["HistoryVideo9"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("")]
        public string HistoryVideo10 {
            get {
                return ((string)(this["HistoryVideo10"]));
            }
            set {
                this["HistoryVideo10"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("5")]
        public int FilesToSave {
            get {
                return ((int)(this["FilesToSave"]));
            }
            set {
                this["FilesToSave"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool SaveBrowserDirectory {
            get {
                return ((bool)(this["SaveBrowserDirectory"]));
            }
            set {
                this["SaveBrowserDirectory"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("")]
        public string BrowserDirectory {
            get {
                return ((string)(this["BrowserDirectory"]));
            }
            set {
                this["BrowserDirectory"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("0.0.0")]
        public string Release {
            get {
                return ((string)(this["Release"]));
            }
            set {
                this["Release"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool ExperimentalRelease {
            get {
                return ((bool)(this["ExperimentalRelease"]));
            }
            set {
                this["ExperimentalRelease"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool ExplorerVisible {
            get {
                return ((bool)(this["ExplorerVisible"]));
            }
            set {
                this["ExplorerVisible"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("100")]
        public int ExplorerSplitterDistance {
            get {
                return ((int)(this["ExplorerSplitterDistance"]));
            }
            set {
                this["ExplorerSplitterDistance"] = value;
            }
        }
    }
}
